### `_config.yml`

```yaml
title: David Mickelson - AI Engineering Manager
email: davidpmickelson@gmail.com
description: >- 
  My professional page showcasing my background, skills, and experience in AI and software engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
twitter_username: your_twitter
github_username: yourusername

markdown: kramdown
theme: minima

# Build settings
plugins:
  - jekyll-feed
